=== Acerik/GTD/DataValidators/flowbasedtopomeasuresdocument-01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="flowbased" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ecc="etso-core-cmpts.xsd" xmlns:fb="flowbased">
	<import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<element name="FlowBasedTopoMeasuresDocument">
		<complexType>
			<sequence>
				<element name="DocumentIdentification" type="ecc:IdentificationType"/>
				<element name="DocumentVersion" type="ecc:VersionType"/>
				<element name="DocumentType" type="ecc:MessageType"/>
				<element name="ProcessType" type="ecc:ProcessType"/>
				<element name="SenderIdentification" type="ecc:PartyType"/>
				<element name="SenderRole" type="ecc:RoleType"/>
				<element name="ReceiverIdentification" type="ecc:PartyType"/>
				<element name="ReceiverRole" type="ecc:RoleType"/>
				<element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<element name="ConstraintTimeInterval" type="ecc:TimeIntervalType"/>
				<element name="Domain" type="ecc:AreaType"/>
				<element minOccurs="0" name="complexVariants" type="fb:complexVariantsType"/>
			</sequence>
			<attribute name="DtdVersion" type="string" use="required"/>
			<attribute name="DtdRelease" type="string" use="required"/>
		</complexType>
	</element>
	<complexType name="complexVariantsType">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="complexVariant" type="fb:independant_complexVariant"/>
		</sequence>
	</complexType>
	<simpleType name="nonEmptyString">
		<restriction base="string">
			<minLength value="1"/>
			<pattern value="([a-zA-Z 0-9_.,()/=!\[\]#%&amp;*;&apos;+:?-])*"/>
		</restriction>
	</simpleType>
	<simpleType name="idString">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="100"/>
		</restriction>
	</simpleType>
	<simpleType name="tso_code">
		<restriction base="string">
			<pattern value="[A-Z0-9]{2}"/>
		</restriction>
	</simpleType>
	<simpleType name="nodeType">
		<restriction base="string">
			<pattern value=".{6}\d(\p{L}|\d| )?"/>
		</restriction>
	</simpleType>
	<complexType name="independant_complexVariant">
		<sequence>
			<element name="timeInterval" type="ecc:TimeIntervalType"/>
			<element name="tsoOrigin" type="fb:tso_code" maxOccurs="1" minOccurs="1"/>
			<element maxOccurs="unbounded" minOccurs="1" name="actionsSet" type="fb:actionsSetType"/>
		</sequence>
		<attribute name="id" type="fb:idString" use="required"/>
		<attribute name="name" type="fb:nonEmptyString"/>
	</complexType>
	<complexType name="actionsSetType">
		<sequence>
			<element maxOccurs="unbounded" name="action" type="fb:actionType"/>
		</sequence>
		<attribute name="name" type="fb:nonEmptyString" use="optional"/>
	</complexType>
	<complexType mixed="true" name="actionType">
		<all>
			<element minOccurs="1" name="branch">
				<complexType>
					<attribute name="from" type="fb:nodeType" use="required"/>
					<attribute name="to" type="fb:nodeType" use="required"/>
					<attribute name="order" use="optional">
						<simpleType>
							<restriction base="string">
								<pattern value="[1-9]|[A-Z]"/>
							</restriction>
						</simpleType>
					</attribute>
					<attribute name="elementName" type="fb:nonEmptyString" use="optional"/>
				</complexType>
				<key name="actionBranch__order_OR_elementName">
					<selector xpath="."/>
					<field xpath="@order|@elementName"/>
				</key>
			</element>
			<element minOccurs="0" name="value" type="fb:nonEmptyString"/>
		</all>
		<attribute name="type" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="STATUS"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
</schema>

=== Acerik/GTD/DataInput/1_IDTDG/F639_10X1001A1001A329-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedTopoMeasuresDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedtopomeasuresdocument-01.xsd">
  <DocumentIdentification v="10X1001A1001A329-20210508-F639v1"/>
  <DocumentVersion v="3"/>
  <DocumentType v="A16"/>
  <ProcessType v="A02"/>
  <SenderIdentification codingScheme="A01" v="10X1001A1001A329"/>
  <SenderRole v="A04"/>
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T"/>
  <ReceiverRole v="A36"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
  <Domain codingScheme="A01" v="10YHU-MAVIR----U"/>
  <complexVariants>
    <complexVariant id="HU_RA_00329" name="PST_ZANDV D1_329">
      <timeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
      <tsoOrigin>HU</tsoOrigin>
      <actionsSet name="TOPO_ZANDV D1">
        <action type="STATUS">
          <branch elementName="ZANDV380 D 1" from="XCEPR120" to="MGOD  12"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
  </complexVariants>
</FlowBasedTopoMeasuresDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F639_10X1001A1001A361-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedTopoMeasuresDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedtopomeasuresdocument-01.xsd">
  <DocumentIdentification v="10X1001A1001A361-20210508-F639v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="A16"/>
  <ProcessType v="A02"/>
  <SenderIdentification codingScheme="A01" v="10X1001A1001A361"/>
  <SenderRole v="A04"/>
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T"/>
  <ReceiverRole v="A36"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
  <Domain codingScheme="A01" v="10YNL----------L"/>
  <complexVariants>
    <complexVariant id="BE_RA_00361" name="PST_ZANDV D1_361">
      <timeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
      <tsoOrigin>NL</tsoOrigin>
      <actionsSet name="TOPO_ZANDV D1">
        <action type="STATUS">
          <branch elementName="AB-AK150 W" from="NAB1503A" to="NAK1503A"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
  </complexVariants>
</FlowBasedTopoMeasuresDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F639_10YCZ-CEPS-----N-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedTopoMeasuresDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedtopomeasuresdocument-01.xsd">
  <DocumentIdentification v="10XCZ-CEPS-GRIDE-20210508-F639v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="A16"/>
  <ProcessType v="A02"/>
  <SenderIdentification codingScheme="A01" v="10XCZ-CEPS-GRIDE"/>
  <SenderRole v="A04"/>
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T"/>
  <ReceiverRole v="A36"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
  <Domain codingScheme="A01" v="10YCZ-CEPS-----N"/>
  <complexVariants>
    <complexVariant id="BE_RA_0CEPS" name="PST_ZANDV D1_CEPS">
      <timeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z"/>
      <tsoOrigin>CZ</tsoOrigin>
      <actionsSet name="TOPO_ZANDV D1">
        <action type="STATUS">
          <branch elementName="MAD:1:nSP:1" from="CMAD__52" to="CMAD__51"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
  </complexVariants>
</FlowBasedTopoMeasuresDocument>
