=== Acerik/GTD/DataValidators/flowbasedexternalconstraintdocument-08.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="flowbased" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ecc="etso-core-cmpts.xsd" xmlns:fb="flowbased">
	<import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<element name="FlowBasedExternalConstraintDocument">
		<complexType>
			<sequence>
				<element name="DocumentIdentification" type="ecc:IdentificationType"/>
				<element name="DocumentVersion" type="ecc:VersionType"/>
				<element name="DocumentType" type="ecc:MessageType"/>
				<element name="ProcessType" type="ecc:ProcessType"/>
				<element name="SenderIdentification" type="ecc:PartyType"/>
				<element name="SenderRole" type="ecc:RoleType"/>
				<element name="ReceiverIdentification" type="ecc:PartyType"/>
				<element name="ReceiverRole" type="ecc:RoleType"/>
				<element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<element name="ExternalConstraintTimeInterval" type="ecc:TimeIntervalType"/>
				<element name="Domain" type="ecc:AreaType"/>
				<element name="constraints" type="fb:constrList">
					<unique name="UniqueConstrId">
						<selector xpath="./fb:netPositionConstraint"/>
						<field xpath="@id"/>
					</unique>
				</element>
			</sequence>
			<attribute name="DtdVersion" type="string" use="required"/>
			<attribute name="DtdRelease" type="string" use="required"/>
		</complexType>
	</element>
	<simpleType name="nonEmptyString">
		<restriction base="string">
			<minLength value="1"/>
		</restriction>
	</simpleType>
	<simpleType name="country">
		<restriction base="string">
			<pattern value="[a-zA-Z0-9_]{2,40}"/>
		</restriction>
	</simpleType>
	<complexType name="tso_type">
		<simpleContent>
			<extension base="fb:tso_code">
				<attribute name="id" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<simpleType name="tso_code">
		<restriction base="string">
			<pattern value="[A-Z0-9]{2,3}"/>
		</restriction>
	</simpleType>
	<simpleType name="timeInterval">
		<restriction base="string">
			<pattern value="\[([01][0-9]|2[0-3]):([0-5][0-9])\-(([01][0-9]|2[0-3]):([0-5][0-9])|24:00)\]"/>
		</restriction>
	</simpleType>
	<simpleType name="hour">
		<restriction base="string">
			<pattern value="([01][0-9]|2[0-3]):([0-5][0-9])"/>
		</restriction>
	</simpleType>
	<complexType name="NetPositionConstraint">
		<sequence>
			<choice maxOccurs="1" minOccurs="1">
				<element name="time">
					<complexType>
						<attribute name="v" type="dateTime"/>
					</complexType>
				</element>
				<element name="timeInterval" type="ecc:TimeIntervalType"/>
			</choice>
			<element minOccurs="0" name="tsoOrigin" type="fb:tso_type"/>
		</sequence>
		<attribute name="id" type="fb:nonEmptyString" use="optional"/>
		<attribute name="value" type="int" use="required"/>
		<attribute name="name" type="string" use="required"/>
		<attribute name="version" type="integer"/>
		<attribute name="hub" type="fb:country" use="required"/>
		<attribute name="direction" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="EXPORT|IMPORT"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="type">
			<simpleType>
				<restriction base="string">
					<pattern value="ABSOLUTE|RELATIVE"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<complexType name="constrList">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="netPositionConstraint" type="fb:NetPositionConstraint"/>
		</sequence>
	</complexType>
</schema>

=== Acerik/GTD/DataInput/1_IDTDG/F634_17XTSO-CS------W-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedExternalConstraintDocument DtdRelease="0" DtdVersion="4" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedexternalconstraintdocument-08.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20190330-F634v1" />
  <DocumentVersion v="1" />
  <DocumentType v="Z11" />
  <ProcessType v="A02"/>
  <SenderIdentification codingScheme="A01" v="17XTSO-CS------W" />
  <SenderRole v="A36" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2021-11-08T09:49:15Z" />
  <ExternalConstraintTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="10Y1001C--00059P"/>
  <constraints>
        <netPositionConstraint direction="EXPORT" hub="BE" id="0" name="BE_export" type="ABSOLUTE" value="4900" version="2">
          <timeInterval v="2019-03-29T23:00Z/2019-03-30T00:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="1" name="BE_import" type="ABSOLUTE" value="4900" version="2">
          <timeInterval v="2019-03-29T23:00Z/2019-03-30T00:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="2" name="BE_export" type="ABSOLUTE" value="4700" version="2">
          <timeInterval v="2019-03-30T00:00Z/2019-03-30T01:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="3" name="BE_import" type="ABSOLUTE" value="4700" version="2">
          <timeInterval v="2019-03-30T00:00Z/2019-03-30T01:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="4" name="BE_export" type="ABSOLUTE" value="4500" version="2">
          <timeInterval v="2019-03-30T01:00Z/2019-03-30T02:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="5" name="BE_import" type="ABSOLUTE" value="4500" version="2">
          <timeInterval v="2019-03-30T01:00Z/2019-03-30T02:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="6" name="BE_export" type="ABSOLUTE" value="4700" version="2">
          <timeInterval v="2019-03-30T02:00Z/2019-03-30T03:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="7" name="BE_import" type="ABSOLUTE" value="4700" version="2">
          <timeInterval v="2019-03-30T02:00Z/2019-03-30T03:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="8" name="BE_export" type="ABSOLUTE" value="5300" version="2">
          <timeInterval v="2019-03-30T03:00Z/2019-03-30T04:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="9" name="BE_import" type="ABSOLUTE" value="5300" version="2">
          <timeInterval v="2019-03-30T03:00Z/2019-03-30T04:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="10" name="BE_export" type="ABSOLUTE" value="5400" version="2">
          <timeInterval v="2019-03-30T04:00Z/2019-03-30T05:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="11" name="BE_import" type="ABSOLUTE" value="5400" version="2">
          <timeInterval v="2019-03-30T04:00Z/2019-03-30T05:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="12" name="BE_export" type="ABSOLUTE" value="5350" version="2">
          <timeInterval v="2019-03-30T05:00Z/2019-03-30T06:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="13" name="BE_import" type="ABSOLUTE" value="5350" version="2">
          <timeInterval v="2019-03-30T05:00Z/2019-03-30T06:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="14" name="BE_export" type="ABSOLUTE" value="5300" version="2">
          <timeInterval v="2019-03-30T06:00Z/2019-03-30T07:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="15" name="BE_import" type="ABSOLUTE" value="5300" version="2">
          <timeInterval v="2019-03-30T06:00Z/2019-03-30T07:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="16" name="BE_export" type="ABSOLUTE" value="5500" version="2">
          <timeInterval v="2019-03-30T07:00Z/2019-03-30T08:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="17" name="BE_import" type="ABSOLUTE" value="5500" version="2">
          <timeInterval v="2019-03-30T07:00Z/2019-03-30T08:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="18" name="BE_export" type="ABSOLUTE" value="5600" version="2">
          <timeInterval v="2019-03-30T08:00Z/2019-03-30T09:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="19" name="BE_import" type="ABSOLUTE" value="5600" version="2">
          <timeInterval v="2019-03-30T08:00Z/2019-03-30T09:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="20" name="BE_export" type="ABSOLUTE" value="5900" version="2">
          <timeInterval v="2019-03-30T09:00Z/2019-03-30T10:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="21" name="BE_import" type="ABSOLUTE" value="5900" version="2">
          <timeInterval v="2019-03-30T09:00Z/2019-03-30T10:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="22" name="BE_export" type="ABSOLUTE" value="6300" version="2">
          <timeInterval v="2019-03-30T10:00Z/2019-03-30T11:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="23" name="BE_import" type="ABSOLUTE" value="6300" version="2">
          <timeInterval v="2019-03-30T10:00Z/2019-03-30T11:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="24" name="BE_export" type="ABSOLUTE" value="6350" version="2">
          <timeInterval v="2019-03-30T11:00Z/2019-03-30T12:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="25" name="BE_import" type="ABSOLUTE" value="6350" version="2">
          <timeInterval v="2019-03-30T11:00Z/2019-03-30T12:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="26" name="BE_export" type="ABSOLUTE" value="6450" version="2">
          <timeInterval v="2019-03-30T12:00Z/2019-03-30T13:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="27" name="BE_import" type="ABSOLUTE" value="6450" version="2">
          <timeInterval v="2019-03-30T12:00Z/2019-03-30T13:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="28" name="BE_export" type="ABSOLUTE" value="6500" version="2">
          <timeInterval v="2019-03-30T13:00Z/2019-03-30T14:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="29" name="BE_import" type="ABSOLUTE" value="6500" version="2">
          <timeInterval v="2019-03-30T13:00Z/2019-03-30T14:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="30" name="BE_export" type="ABSOLUTE" value="6000" version="2">
          <timeInterval v="2019-03-30T14:00Z/2019-03-30T15:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="31" name="BE_import" type="ABSOLUTE" value="6000" version="2">
          <timeInterval v="2019-03-30T14:00Z/2019-03-30T15:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="32" name="BE_export" type="ABSOLUTE" value="5500" version="2">
          <timeInterval v="2019-03-30T15:00Z/2019-03-30T16:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="BE" id="33" name="BE_import" type="ABSOLUTE" value="5500" version="2">
          <timeInterval v="2019-03-30T15:00Z/2019-03-30T16:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="BE" id="34" name="BE_export" type="ABSOLUTE" value="5600" version="2">
          <timeInterval v="2019-03-30T16:00Z/2019-03-30T17:00Z"/>
          <tsoOrigin>BE</tsoOrigin>
        </netPositionConstraint>
