=== Acerik/GTD/DataValidators/gsk-document-04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v2011 rel2 (http://www.xmlspy.com) by Guillaneau (RTE) -->
<xsd:schema xmlns:ecc="etso-core-cmpts.xsd" xmlns:ecl="etso-code-lists.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd" />
	<xsd:import namespace="etso-code-lists.xsd" schemaLocation="etso-code-lists.xsd" />
	<xsd:element name="GSKDocument">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="DocumentIdentification" type="ecc:IdentificationType" />
				<xsd:element name="DocumentVersion" type="ecc:VersionType" />
				<xsd:element name="DocumentType" type="ecc:MessageType" />
				<xsd:element name="ProcessType" type="ecc:ProcessType" />
				<xsd:element name="SenderIdentification" type="ecc:PartyType" />
				<xsd:element name="SenderRole" type="ecc:RoleType" />
				<xsd:element name="ReceiverIdentification" type="ecc:PartyType" />
				<xsd:element name="ReceiverRole" type="ecc:RoleType" />
				<xsd:element name="CreationDateTime" type="ecc:MessageDateTimeType" />
				<xsd:element name="GSKTimeInterval" type="ecc:TimeIntervalType" />
				<xsd:element name="Domain" type="ecc:AreaType" />
				<xsd:element name="GSKSeries" type="GSKSeries_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Reason" type="Reason_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="DtdRelease" type="xsd:string" use="optional" />
			<xsd:attribute name="DtdVersion" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="GSKSeries_Type">
		<xsd:sequence>
			<xsd:element name="TimeSeriesIdentification" type="ecc:IdentificationType" />
			<xsd:element name="BusinessType" type="BusinessTypeWithShare" />
			<xsd:element name="Area" type="ecc:AreaType" />
			<xsd:element name="ManualGSK_Block" type="ManualGSK_Block_Type" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="CountryGSK_Block" type="CountryGSK_Block_Type" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="AutoGSK_Block" type="AutoGSK_Block_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
<!--____Dedicated GSK-specific Business type which contains share attribute using ShareType____-->
	<xsd:complexType name="BusinessTypeWithShare">
		<xsd:annotation>
			<xsd:documentation>
				<Uid>ET0017-2</Uid>
				<Definition>The exact business nature identifying the principal characteristic of a time series.</Definition>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="v" type="ecl:BusinessTypeList" use="required"/>
		<xsd:attribute name="share" type="ShareType" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="ShareType">
		<xsd:annotation>
			<xsd:documentation>
				<Uid>ET0050</Uid>
				<Definition>Value identifying ration between generation and load in country and auto nodes.</Definition>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!--_________________________________________________-->
	<xsd:complexType name="ManualGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType" />
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType" />
			<xsd:element name="ManualNodes" type="ManualNodes_Type" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManualNodes_Type">
		<xsd:sequence>
			<xsd:element name="NodeName" type="ecc:IdentificationType" />
			<xsd:element name="Factor" type="ecc:QuantityType" />
			<xsd:element name="Status" type="GenStatus_Type" minOccurs="0" />
			<xsd:element name="ActiveGen" type="ecc:QuantityType" minOccurs="0" />
			<xsd:element name="ReactiveGen" type="ecc:QuantityType" minOccurs="0" />
			<xsd:element name="InitActiveLoad" type="ecc:QuantityType" minOccurs="0" />
			<xsd:element name="ReactiveLoad" type="ecc:QuantityType" minOccurs="0" />
			<xsd:element name="EstimatedLoss" type="ecc:QuantityType" minOccurs="0" />
			<xsd:element name="OriginalFactor" type="ecc:QuantityType" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AutoGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType" />
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType" />
			<xsd:element name="AutoNodes" type="AutoNodes_Type" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AutoNodes_Type">
		<xsd:sequence>
			<xsd:element name="NodeName" type="ecc:IdentificationType" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CountryGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType" />
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Reason_Type">
		<xsd:sequence>
			<xsd:element name="ReasonCode" type="ecc:ReasonCodeType" />
			<xsd:element name="ReasonText" type="ecc:ReasonTextType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="GenStatus_Type">
		<xsd:attribute name="v" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="OK" />
					<xsd:enumeration value="NOK" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== Acerik/GTD/DataInput/1_IDTDG/F607_10XDE-RWENET---W-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document-04.xsd">
  <DocumentIdentification v="10XDE-RWENET---W-20201126F607v1" />
  <DocumentVersion v="1"/>
  <DocumentType v="B22" />
  <ProcessType v="A02" />
  <SenderIdentification codingScheme="A01" v="10XDE-RWENET---W" />
  <SenderRole v="A04" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2020-11-24T21:00:01Z" />
  <GSKTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="10YDE-RWENET---I" />
  <GSKSeries>
    <TimeSeriesIdentification v="1" />
    <BusinessType v="Z02" share="100" />
    <Area codingScheme="A01" v="10YDE-RWENET---I" />
    <ManualGSK_Block>
      <GSK_Name v="D7" />
      <TimeInterval v="2019-03-29T23:00Z/2019-03-30T05:00Z" />
      <ManualNodes>
        <NodeName v="D7BERG7A" />
        <Factor v="0.1077" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD70" />
        <Factor v="0.0362" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD71" />
        <Factor v="0.0381" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD72" />
        <Factor v="0.0381" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7HERN74" />
        <Factor v="0.0436" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7GEIT72" />
        <Factor v="0.0453" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWIB7B" />
        <Factor v="0.1233" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN7B" />
        <Factor v="0.0479" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN71" />
        <Factor v="0.0301" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7B" />
        <Factor v="0.0513" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7C" />
        <Factor v="0.0513" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWST70" />
        <Factor v="0.0815" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWA79" />
        <Factor v="0.0539" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWS7E" />
        <Factor v="0.1029" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWDA71" />
        <Factor v="0.1488" />
      </ManualNodes>
    </ManualGSK_Block>
    <ManualGSK_Block>
      <GSK_Name v="D7" />
      <TimeInterval v="2019-03-30T05:00Z/2019-03-30T21:00Z" />
      <ManualNodes>
        <NodeName v="D7BERG7A" />
        <Factor v="0.091" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD70" />
        <Factor v="0.031" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD71" />
        <Factor v="0.032" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD72" />
        <Factor v="0.032" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSB70" />
        <Factor v="0.034" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSC70" />
        <Factor v="0.036" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7HERN74" />
        <Factor v="0.037" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7GEIT71" />
        <Factor v="0.038" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7GEIT72" />
        <Factor v="0.038" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWIB7B" />
        <Factor v="0.104" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN7B" />
        <Factor v="0.04" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN71" />
        <Factor v="0.025" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN72" />
        <Factor v="0.025" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN70" />
        <Factor v="0.025" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7B" />
        <Factor v="0.043" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7C" />
        <Factor v="0.043" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWST70" />
        <Factor v="0.069" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWA79" />
        <Factor v="0.045" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWS7E" />
        <Factor v="0.087" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWDA71" />
        <Factor v="0.125" />
      </ManualNodes>
    </ManualGSK_Block>
    <ManualGSK_Block>
      <GSK_Name v="D7" />
      <TimeInterval v="2019-03-30T21:00Z/2019-03-30T23:00Z" />
      <ManualNodes>
        <NodeName v="D7BERG7A" />
        <Factor v="0.1077" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD70" />
        <Factor v="0.0362" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD71" />
        <Factor v="0.0381" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7EMSD72" />
        <Factor v="0.0381" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7HERN74" />
        <Factor v="0.0436" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7GEIT72" />
        <Factor v="0.0453" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWIB7B" />
        <Factor v="0.1233" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN7B" />
        <Factor v="0.0479" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWKN71" />
        <Factor v="0.0301" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7B" />
        <Factor v="0.0513" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7SHOL7C" />
        <Factor v="0.0513" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWST70" />
        <Factor v="0.0815" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWA79" />
        <Factor v="0.0539" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWWS7E" />
        <Factor v="0.1029" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D7KWDA71" />
        <Factor v="0.1488" />
      </ManualNodes>
    </ManualGSK_Block>
  </GSKSeries>
</GSKDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F607_22Y201903144---9-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document-04.xsd">
  <DocumentIdentification v="22Y201903144---9-20201126F607v1" />
  <DocumentVersion v="1"/>
  <DocumentType v="B22" />
  <ProcessType v="A02" />
  <SenderIdentification codingScheme="A01" v="22Y201903144---9" />
  <SenderRole v="A04" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2020-11-24T21:00:02Z" />
  <GSKTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="22Y201903144---9" />
  <GSKSeries>
    <TimeSeriesIdentification v="1" />
    <BusinessType v="Z02" share="100" />
    <Area codingScheme="A01" v="22Y201903144---9" />
    <ManualGSK_Block>
      <GSK_Name v="BE_AL" />
      <TimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
      <ManualNodes>
        <NodeName v="XLI_OB1B" />
        <Factor v="1" />
      </ManualNodes>
    </ManualGSK_Block>
  </GSKSeries>
</GSKDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F607_10XRO-TEL------2-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document-04.xsd">
  <DocumentIdentification v="10XRO-TEL------2-20201126F607v1" />
  <DocumentVersion v="1"/>
  <DocumentType v="B22" />
  <ProcessType v="A02" />
  <SenderIdentification codingScheme="A01" v="10XRO-TEL------2" />
  <SenderRole v="A04" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2020-11-24T21:00:01Z" />
  <GSKTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="10YRO-TEL------P" />
  <GSKSeries>
    <TimeSeriesIdentification v="1" />
    <BusinessType v="Z02" share="100" />
    <Area codingScheme="A01" v="10YRO-TEL------P" />
    <AutoGSK_Block>
      <GSK_Name v="RO" />
      <TimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
      <AutoNodes>
        <NodeName v="RCTCVA5 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RCTCVB5 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RGILC22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RIERN15 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RIERN22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RISAL22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RLOTR22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RMARI22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RMUNT_5 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="ROSTRB5 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RPDF212 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RPDF222 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RREME_5 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RRETE22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RROVI31 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RSUGA22 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RTHARG2 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RTURC11 " />
      </AutoNodes>
      <AutoNodes>
        <NodeName v="RTURC51 " />
      </AutoNodes>
    </AutoGSK_Block>
  </GSKSeries>
</GSKDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F607_10XFR-RTE------Q-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document-04.xsd">
  <DocumentIdentification v="10XFR-RTE------Q-20201126F607v1" />
  <DocumentVersion v="1"/>
  <DocumentType v="B22" />
  <ProcessType v="A02" />
  <SenderIdentification codingScheme="A01" v="10XFR-RTE------Q" />
  <SenderRole v="A04" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2020-11-24T21:00:01Z" />
  <GSKTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="10YFR-RTE------C" />
  <GSKSeries>
    <TimeSeriesIdentification v="1" />
    <BusinessType v="Z02" share="100" />
    <Area codingScheme="A01" v="10YFR-RTE------C" />
    <CountryGSK_Block>
      <GSK_Name v="FR" />
      <TimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
    </CountryGSK_Block>
  </GSKSeries>
</GSKDocument>

=== Acerik/GTD/DataInput/1_IDTDG/F607_10XDE-EON-NETZ-C-to-10V1001C--00264T.xml
<?xml version='1.0' encoding='UTF-8'?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document-04.xsd">
  <DocumentIdentification v="10XDE-EON-NETZ-C-20201126F607v1" />
  <DocumentVersion v="1"/>
  <DocumentType v="B22" />
  <ProcessType v="A02" />
  <SenderIdentification codingScheme="A01" v="10XDE-EON-NETZ-C" />
  <SenderRole v="A04" />
  <ReceiverIdentification codingScheme="A01" v="10V1001C--00264T" />
  <ReceiverRole v="A36" />
  <CreationDateTime v="2020-11-24T21:00:01Z" />
  <GSKTimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
  <Domain codingScheme="A01" v="10YDE-EON------1" />
  <GSKSeries>
    <TimeSeriesIdentification v="1" />
    <BusinessType v="Z02" share="100" />
    <Area codingScheme="A01" v="10YDE-EON------1" />
    <ManualGSK_Block>
      <GSK_Name v="D2" />
      <TimeInterval v="2019-03-29T23:00Z/2019-03-30T23:00Z" />
      <ManualNodes>
        <NodeName v="D2ERZH21" />
        <Factor v="0.0263" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2ERZH22" />
        <Factor v="0.0263" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2ETZ 51" />
        <Factor v="0.0248" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2GEB 51" />
        <Factor v="0.1321" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2GKRO1C" />
        <Factor v="0.0756" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2HEYD11" />
        <Factor v="0.1303" />
      </ManualNodes>
      
      <ManualNodes>
        <NodeName v="D2KHT 2A" />
        <Factor v="0.0244" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2KHT 2B" />
        <Factor v="0.0244" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2LU  51" />
        <Factor v="0.0392" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2MEHR21" />
        <Factor v="0.074" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2OBR 51" />
        <Factor v="0.0186" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2SLZ 2A" />
        <Factor v="0.0516" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2SLZ 2B" />
        <Factor v="0.0516" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2WALD1A" />
        <Factor v="0.0439" />
      </ManualNodes>
     
      <ManualNodes>
        <NodeName v="D2WHAV21" />
        <Factor v="0.1075" />
      </ManualNodes>
      <ManualNodes>
        <NodeName v="D2ZOL 2A" />
        <Factor v="0.0712" />
      </ManualNodes>
    </ManualGSK_Block>
  </GSKSeries>
</GSKDocument>
